/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/popup/routes/__root'

// Create Virtual Routes

const JobsLazyImport = createFileRoute('/jobs')()
const JobsAddLazyImport = createFileRoute('/jobs/add')()
const JobsJobIdLazyImport = createFileRoute('/jobs/$jobId')()

// Create/Update Routes

const JobsLazyRoute = JobsLazyImport.update({
  path: '/jobs',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./pages/popup/routes/jobs.lazy').then((d) => d.Route),
)

const JobsAddLazyRoute = JobsAddLazyImport.update({
  path: '/add',
  getParentRoute: () => JobsLazyRoute,
} as any).lazy(() =>
  import('./pages/popup/routes/jobs.add.lazy').then((d) => d.Route),
)

const JobsJobIdLazyRoute = JobsJobIdLazyImport.update({
  path: '/$jobId',
  getParentRoute: () => JobsLazyRoute,
} as any).lazy(() =>
  import('./pages/popup/routes/jobs.$jobId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jobs': {
      preLoaderRoute: typeof JobsLazyImport
      parentRoute: typeof rootRoute
    }
    '/jobs/$jobId': {
      preLoaderRoute: typeof JobsJobIdLazyImport
      parentRoute: typeof JobsLazyImport
    }
    '/jobs/add': {
      preLoaderRoute: typeof JobsAddLazyImport
      parentRoute: typeof JobsLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  JobsLazyRoute.addChildren([JobsJobIdLazyRoute, JobsAddLazyRoute]),
])

/* prettier-ignore-end */
