version: "3.8"
services:
  headless-shell:
    image: chromedp/headless-shell
    ports:
      - "9222:9222"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # volumes:
    #   - ./backend:/app
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - headless-shell
