server:
  port: "8080"
  host: "0.0.0.0"
  clientAddress: "*"
firebase:
  storageBucket: "application-tracker-dev.appspot.com"
  projectId: "application-tracker-dev"
  credentialsBase64: "will be set by environment variable"
