screenshot:
  width: 1920
  height: 1080
  delayInSeconds: "10s"
  endDelayInSeconds: "25s"
  retries: 3
  headlessUrl: "ws://localhost:9222/"
server:
  port: "8080"
  host: "0.0.0.0"
  clientAddress: "http://localhost:3000"
firebase:
  storageBucket: "application-tracker-dev.appspot.com"
  projectId: "application-tracker-dev"
  credentialsBase64: "will be set by environment variable"
