/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const JobsLazyImport = createFileRoute('/jobs')()
const JobsAddLazyImport = createFileRoute('/jobs/add')()
const JobsAddmodalLazyImport = createFileRoute('/jobs/addmodal')()
const JobsJobIdLazyImport = createFileRoute('/jobs/$jobId')()

// Create/Update Routes

const JobsLazyRoute = JobsLazyImport.update({
  path: '/jobs',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/jobs.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const JobsAddLazyRoute = JobsAddLazyImport.update({
  path: '/jobs/add',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/jobs_.add.lazy').then((d) => d.Route))

const JobsAddmodalLazyRoute = JobsAddmodalLazyImport.update({
  path: '/addmodal',
  getParentRoute: () => JobsLazyRoute,
} as any).lazy(() => import('./routes/jobs.addmodal.lazy').then((d) => d.Route))

const JobsJobIdLazyRoute = JobsJobIdLazyImport.update({
  path: '/$jobId',
  getParentRoute: () => JobsLazyRoute,
} as any).lazy(() => import('./routes/jobs.$jobId.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/jobs': {
      preLoaderRoute: typeof JobsLazyImport
      parentRoute: typeof rootRoute
    }
    '/jobs/$jobId': {
      preLoaderRoute: typeof JobsJobIdLazyImport
      parentRoute: typeof JobsLazyImport
    }
    '/jobs/addmodal': {
      preLoaderRoute: typeof JobsAddmodalLazyImport
      parentRoute: typeof JobsLazyImport
    }
    '/jobs/add': {
      preLoaderRoute: typeof JobsAddLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  JobsLazyRoute.addChildren([JobsJobIdLazyRoute, JobsAddmodalLazyRoute]),
  JobsAddLazyRoute,
])

/* prettier-ignore-end */
