name: Lint and Test Frontend
on:
  push:
    branches: [main]
    paths: ["frontend/**", ".github/workflows/frontend.yml"]
  pull_request:
    branches: [main]
    paths: ["frontend/**", ".github/workflows/frontend.yml"]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install Dependencies
        run: pnpm install
        working-directory: frontend
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - name: Install Dependencies
        run: pnpm install
        working-directory: frontend
      - name: Lint
        run: pnpm run lint
        working-directory: frontend
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - name: Install Dependencies
        run: pnpm install
        working-directory: frontend
      - name: Run Tests
        run: pnpm run test
        working-directory: frontend
